## Macroecological model-fitting parameters underlying Fig. 3B

library(tidyverse)
library(openxlsx)

## 1. Load objects generated by Figure 3B scripts

load("MacLawDataestimate.Rdata")

## Expected objects:
## proj, gamma_pars, mean_pars

treatment_order = c("D0", "D1", "D3", "D5", "D6", "D7")


## 2. Helper functions

calc_aic = function(loglik, k) {-2 * loglik + 2 * k  }

calc_bic = function(loglik, k, n) { -2 * loglik + log(n) * k }

safe_ks_gamma = function(x, shape, rate) {
  out = suppressWarnings(
    tryCatch(
      ks.test(x, "pgamma", shape = shape, rate = rate),
      error = function(e) NULL
    )
  )
  
  if (is.null(out)) {
    return(tibble(`Goodness-of-fit statistic` = NA_real_,
                  `Goodness-of-fit P` = NA_real_  ))
  } else {
    return(tibble(`Goodness-of-fit statistic` = as.numeric(out$statistic),
                  `Goodness-of-fit P` = out$p.value  ))
  }
}

safe_ks_lognormal = function(x, meanlog, sdlog) {
  out = suppressWarnings(
    tryCatch(
      ks.test(x, "plnorm", meanlog = meanlog, sdlog = sdlog),
      error = function(e) NULL
    )
  )
  
  if (is.null(out)) {
    return(tibble(`Goodness-of-fit statistic` = NA_real_,
                  `Goodness-of-fit P` = NA_real_ ))
  } else {
    return(tibble(`Goodness-of-fit statistic` = as.numeric(out$statistic),
                  `Goodness-of-fit P` = out$p.value  ))
  }
}

## 3. Sheet 1: AFD_Gamma_fit
## Here AFD is fitted to normalized abundance fluctuations:
## relative abundance / OTU-level mean relative abundance.
## This gives positive values suitable for Gamma fitting.

afd_raw = proj %>%
  filter(o > 0.9) %>%                       # high-occupancy OTUs, as in Fig. 3B AFD script
  mutate( relative_abundance = count / nreads  ) %>%
  group_by(sname, otu_id) %>%
  mutate(otu_mean_relative_abundance = mean(relative_abundance, na.rm = T),
         normalized_fluctuation = relative_abundance / otu_mean_relative_abundance  ) %>%
  ungroup() %>%
  filter(is.finite(normalized_fluctuation),  normalized_fluctuation > 0  )

afd_gamma_fit = afd_raw %>%
  group_by(sname) %>%
  group_modify(~ {
    
    x = .x$normalized_fluctuation
    x = x[is.finite(x) & x > 0]
    
    n = length(x)
    
    if (n < 5 || var(x) == 0) {
      return(tibble(`Gamma shape` = NA_real_,
                    `Gamma scale` = NA_real_,
                    `Gamma rate` = NA_real_,
                    `Goodness-of-fit statistic` = NA_real_,
                    `Goodness-of-fit P` = NA_real_,
                    AIC = NA_real_,
                    BIC = NA_real_,
                    `No. observations` = n,
                    `No. OTUs` = n_distinct(.x$otu_id)  ))
    }
    
    ## Method-of-moments Gamma parameters
    shape = mean(x)^2 / var(x)
    scale = var(x) / mean(x)
    rate  = 1 / scale
    
    loglik = sum(dgamma(x, shape = shape, rate = rate, log = T))
    
    gof = safe_ks_gamma(x, shape, rate)
    
    tibble(`Gamma shape` = shape,
           `Gamma scale` = scale,
           `Gamma rate` = rate,
           `Goodness-of-fit statistic` = gof$`Goodness-of-fit statistic`,
           `Goodness-of-fit P` = gof$`Goodness-of-fit P`,
           AIC = calc_aic(loglik, k = 2),
           BIC = calc_bic(loglik, k = 2, n = n),
           `No. observations` = n,
           `No. OTUs` = n_distinct(.x$otu_id)  )  }) %>%
  ungroup() %>%
  mutate(sname = factor(sname, levels = treatment_order)  ) %>%
  arrange(sname) %>%
  rename(`Treatment` = sname)

## 4. Sheet 2: Taylor_law
## Figure 3B uses binned Taylor's law plotting data.
## We fit the log-log relationship to the binned data and report
## the number of OTUs used to generate those bins.

nbins = 20

taylor_binned = gamma_pars %>%
  filter(f > 0, vf > 0) %>%
  group_by(idall, sname) %>%
  mutate(lf = log(f), dlf = (max(lf) - min(lf)) / nbins ) %>%
  mutate(b = as.integer((lf - min(lf)) / dlf)  ) %>%
  ungroup() %>%
  group_by(idall, sname, b) %>%
  summarise(vf = mean(vf, na.rm = T), f = mean(f, na.rm = T), .groups = "drop") %>%
  filter(f > 0, vf > 0) %>%
  mutate(log10_mean_abundance = log10(f), log10_variance_abundance = log10(vf) )

otu_counts_for_taylor = gamma_pars %>%
  filter(f > 0, vf > 0) %>%
  group_by(sname) %>%
  summarise(`No. OTUs` = n_distinct(otu_id), .groups = "drop" )

taylor_law = taylor_binned %>%
  group_by(sname) %>%
  group_modify(~ {
    fit = lm(log10_variance_abundance ~ log10_mean_abundance, data = .x)
    fit_sum = summary(fit)
    
    fstat = fit_sum$fstatistic
    
    pval = pf(fstat[1], fstat[2], fstat[3], lower.tail = F )
    
    tibble(Intercept = unname(coef(fit)[1]),
           Slope = unname(coef(fit)[2]),
           `R2` = fit_sum$r.squared,
           `Adjusted R2` = fit_sum$adj.r.squared,
           `P value` = pval,
           `No. binned points` = nrow(.x)  )  }) %>%
  ungroup() %>%
  left_join(otu_counts_for_taylor, by = "sname") %>%
  mutate(sname = factor(sname, levels = treatment_order)  ) %>%
  arrange(sname) %>%
  rename(`Treatment` = sname)

## 5. Sheet 3: MAD_lognormal_fit
## Use mean_pars$mu and mean_pars$sigma, which are the parameters
## used to generate the lognormal curve in Fig. 3B.

mad_raw = gamma_pars %>%
  filter(f > 0) %>%
  left_join(
    mean_pars %>%
      select(idall, sname, c, mu, sigma),
    by = c("idall", "sname")  ) %>%
  mutate( lf = log(f)  ) %>%
  filter(is.finite(lf),
         lf > c,
         is.finite(mu),
         is.finite(sigma),
         sigma > 0  )

mad_lognormal_fit = mad_raw %>%
  group_by(sname, mu, sigma) %>%
  group_modify(~ {
    
    x = .x$f
    x = x[is.finite(x) & x > 0]
    
    n = length(x)
    meanlog = unique(.y$mu)
    sdlog   = unique(.y$sigma)
    
    if (n < 5 || !is.finite(meanlog) || !is.finite(sdlog) || sdlog <= 0) {
      return(tibble(Meanlog = meanlog,
                    Sdlog = sdlog,
                    `Goodness-of-fit statistic` = NA_real_,
                    `Goodness-of-fit P` = NA_real_,
                    AIC = NA_real_,
                    BIC = NA_real_,
                    `No. OTUs` = n ))
    }
    
    loglik = sum(dlnorm(x, meanlog = meanlog, sdlog = sdlog, log = T))
    
    gof = safe_ks_lognormal(x, meanlog, sdlog)
    
    tibble(Meanlog = meanlog,
           Sdlog = sdlog,
           `Goodness-of-fit statistic` = gof$`Goodness-of-fit statistic`,
           `Goodness-of-fit P` = gof$`Goodness-of-fit P`,
           AIC = calc_aic(loglik, k = 2),
           BIC = calc_bic(loglik, k = 2, n = n),
           `No. OTUs` = n )  }) %>%
  ungroup() %>%
  mutate(sname = factor(sname, levels = treatment_order)  ) %>%
  arrange(sname) %>% 
  rename(`Treatment` = sname)

##  Export Excel workbook

wb = createWorkbook()

addWorksheet(wb, "1.AFD_Gamma_fit")
writeData(wb, "1.AFD_Gamma_fit", afd_gamma_fit)

addWorksheet(wb, "2.Taylor_law")
writeData(wb, "2.Taylor_law", taylor_law)

addWorksheet(wb, "3.MAD_lognormal_fit")
writeData(wb, "3.MAD_lognormal_fit", mad_lognormal_fit)

saveWorkbook( wb,  "Table_S9_macroecological_model_fitting_parameters_underlying_Fig3B.xlsx",  overwrite = T)



